import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const siteOrigin = "https://www.marcosbodi.com";
const generatedMarker = "<!-- Generated by portfolio admin. Do not edit manually. -->";
const videoExtensions = new Set([".mp4", ".mov", ".webm"]);

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeScriptString(value = "") {
  return JSON.stringify(String(value));
}

function getFileStem(fileName = "") {
  return fileName.replace(/\.[^.]+$/, "");
}

function isVideoFile(fileName = "") {
  return videoExtensions.has(extname(fileName).toLowerCase());
}

function getPosterFileName(fileName = "") {
  return `${getFileStem(fileName)}_poster.jpg`;
}

function encodeUrlPath(path = "") {
  return path
    .split("/")
    .map((part) => part ? encodeURIComponent(part) : "")
    .join("/");
}

function absoluteUrl(path = "/") {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return `${siteOrigin}${encodeUrlPath(normalized)}`;
}

function cleanDescription(project = {}) {
  return project.description || project.summary || `${project.title || "Project"} by Marcos Bodi.`;
}

function getProjectImagePath(project = {}) {
  const coverFile = project?.media?.cover?.file || project?.media?.main?.file || "";
  const imageFile = isVideoFile(coverFile) ? getPosterFileName(coverFile) : coverFile;

  return imageFile
    ? `/assets/projects/${project.slug}/${imageFile}`
    : "/assets/projects/dron/cover_optimized.jpg";
}

export function getProjectPagePath(project = {}) {
  return `/projects/${encodeURIComponent(project.slug)}.html`;
}

export function getProjectPageUrl(project = {}) {
  return absoluteUrl(getProjectPagePath(project));
}

export function getProjectSocialImageUrl(project = {}) {
  return absoluteUrl(getProjectImagePath(project));
}

function createProjectSeoHtml(project = {}) {
  const title = `${project.title || "Project"} - Marcos Bodi`;
  const description = cleanDescription(project);
  const url = getProjectPageUrl(project);
  const image = getProjectSocialImageUrl(project);
  const imageAlt = project?.media?.cover?.alt || project.title || "Marcos Bodi project preview";

  return `${generatedMarker}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(description)}" />
  <link rel="canonical" href="${escapeHtml(url)}" />
  <meta name="robots" content="index, follow" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="article" />
  <meta property="og:site_name" content="Marcos Bodi" />
  <meta property="og:title" content="${escapeHtml(title)}" />
  <meta property="og:description" content="${escapeHtml(description)}" />
  <meta property="og:url" content="${escapeHtml(url)}" />
  <meta property="og:image" content="${escapeHtml(image)}" />
  <meta property="og:image:alt" content="${escapeHtml(imageAlt)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escapeHtml(title)}" />
  <meta name="twitter:description" content="${escapeHtml(description)}" />
  <meta name="twitter:image" content="${escapeHtml(image)}" />
  <link rel="stylesheet" href="/css/style.css" />
</head>
<body>
  <header class="site-header">
    <nav class="main-nav main-nav-primary" aria-label="Primary navigation">
      <a href="/about.html">About</a>
    </nav>
    <a class="logo" href="/index.html" aria-label="Marcos Bodi home">MB</a>
    <nav class="main-nav main-nav-social" aria-label="Social navigation">
      <a href="https://www.instagram.com/bodimarcos/" target="_blank" rel="noreferrer">Instagram</a>
    </nav>
  </header>

  <main class="project-page" data-project-root></main>

  <footer class="site-footer project-footer">
    <a href="/index.html" data-next-project-link>Next project &rarr;</a>
    <p>&copy; Marcos Bodi</p>
  </footer>

  <script>window.PORTFOLIO_PROJECT_SLUG = ${escapeScriptString(project.slug)};</script>
  <script src="/data/projects.js"></script>
  <script src="/js/media-render.js"></script>
  <script src="/js/render-project.js"></script>
  <script src="/js/title-brush.js"></script>
  <script src="/js/project-media.js"></script>
  <script src="/js/project-magnetic-dots.js"></script>
  <script src="/js/copy-email.js"></script>
  <script src="/js/site-cursor.js"></script>
</body>
</html>
`;
}

async function pruneStaleGeneratedPages(projectsDir, expectedFiles) {
  let entries = [];

  try {
    entries = await readdir(projectsDir, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") {
      return;
    }

    throw error;
  }

  await Promise.all(entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".html") && !expectedFiles.has(entry.name))
    .map(async (entry) => {
      const filePath = join(projectsDir, entry.name);
      const contents = await readFile(filePath, "utf8");

      if (contents.includes(generatedMarker)) {
        await rm(filePath, { force: true });
      }
    }));
}

export async function generateProjectSeoPages(projects = [], rootDir = process.cwd()) {
  const publicProjects = projects.filter((project) => project?.slug && !project.hidden);
  const projectsDir = resolve(rootDir, "projects");
  const expectedFiles = new Set(publicProjects.map((project) => `${project.slug}.html`));

  await mkdir(projectsDir, { recursive: true });
  await pruneStaleGeneratedPages(projectsDir, expectedFiles);

  await Promise.all(publicProjects.map((project) => writeFile(
    join(projectsDir, `${project.slug}.html`),
    createProjectSeoHtml(project)
  )));

  return publicProjects.length;
}

async function runFromCli() {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const rootDir = resolve(scriptDir, "..");
  const projectsFile = await readFile(resolve(rootDir, "data", "projects.js"), "utf8");
  const projectsJson = projectsFile
    .replace(/^window\.PORTFOLIO_PROJECTS\s*=\s*/, "")
    .replace(/;\s*$/, "");
  const projects = JSON.parse(projectsJson);
  const count = await generateProjectSeoPages(projects, rootDir);
  console.log(`Generated ${count} project SEO page${count === 1 ? "" : "s"}.`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runFromCli().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
